### ISSUE TITLE
Charter font shape undefined

### ISSUE THREAD

**Issue by LucaFranceschini** [programming-journal/programming#16]
When compiling the example with XeTeX or LuaTeX (as suggested) I get the following message:

    LaTeX Font Warning: Font shape `TU/mdbch/m/n' undefined
    (Font)              using `TU/lmr/m/n' instead on input line 105.

The warning seems to be generated by the `fontspec` package and it is related to the charter font.

MWE, discussion and possible workarounds can be found [here](https://tex.stackexchange.com/q/401481/63917).

I am using TeX Live 2017.

**Comment by krono** [comment]
Thanks for the good issue and MWE and link.
This problem is worked-around in the master version (version 1.3). A manual workaround can be found in the stackexchange discussion.
