### ISSUE TITLE
doclicense-related incompatibility with MiKTeX

### ISSUE THREAD

**Issue by amintos** [programming-journal/programming#17]
Building the example with current MiKTeX pdflatex (2017-11-14) produces
```
! LaTeX Error: File `doclicense-CC-by' not found.
```
In fact, this exact file is not included in the current version of MiKTeX' _doclicense_ package:
https://miktex.org/Package/Browse/doclicense

Workarounds:

- Remain at old version (e.g.  from 2017-09-03) 
- Copy _images_ directory from [original package](https://ctan.org/tex-archive/macros/latex/contrib/doclicense/images) to```<MiKTeX-root>\tex\latex\doclicense```, then run ```mpm --update-db```

**Comment by krono** [comment]
Yes, that was a problem with TeXLive 2016 too. It was fixed there.

What could I do?

**Comment by amintos** [comment]
Just wanted to have it documented in case anyone runs into the same issue shortly before the December deadline.

Thanks to the quick response from @edocevoli, everything is back to normal: https://github.com/MiKTeX/miktex-packaging/issues/11 😉

**Comment by krono** [comment]
Thanks :)
