### ISSUE TITLE
LaTeX error when using code=mono

### ISSUE THREAD

**Issue by VijayKrishna** [programming-journal/programming#19]
I am hitting this error: 
```
TraditionalBuilder: Engine: pdflatex. Invoking latexmk... done.

Errors:

/usr/local/texlive/2015/texmf-dist/tex/latex/fira/FiraMono.sty:34: LaTeX Error: Unknown option `nomap' for package `FiraMono'. []
```
 when i setup the document class as follows:
`\documentclass[english,submission,code=mono]{programming}`. What am I missing?

I am using Sublime's LaTeXTools and pdftex is my LaTeX engine.

**Comment by krono** [comment]
Can you please post the logfile to https://gist.github.com/ and link it here?

**Comment by VijayKrishna** [comment]
My MacTeX distribution was out-of-date (it was a 2015 installation). Upgrading to MacTeX 2017 fixed the issue for me.

**Comment by krono** [comment]
Glad to hear. Thanks
