### ISSUE TITLE
Formatting issue with the Programming tempalte

### ISSUE THREAD

**Issue by brosenan** [programming-journal/programming#3]
When rendering our paper we see the following issue in the copyright notice at the from page:
a space is missing between the first author's name and the the word "and".

![image](https://cloud.githubusercontent.com/assets/2514000/21840850/61cdf65e-d7e8-11e6-83b6-10e064eda871.png)

**Comment by krono** [comment]
Thanks for reporting.

A Quickfix for submission: add directly after `\documentclass`

```LaTeX
\makeatletter
\renewcommand*\P@author@[2][]{%
  \gdef\P@last@author{#2}%
  \listgadd\P@authors{%
    \P@author@link{#2}\ignorespaces%
    \P@affil{#1}\relax}%
  \stepcounter{P@authors}%
  \P@author@serialize%
}
\makeatother
```
