### ISSUE TITLE
Font shape declaration has incorrect series value `mc'.

### ISSUE THREAD

**Issue by svdvonde** [programming-journal/programming#34]
The template currently produces 16 of the following warnings: 

```LaTeX Warning: Font shape declaration has incorrect series value `mc'.
               It should not contain an `m'! Please correct it.```

The cause of this seems to be the `mathdesign` package, and more specifically its deprecated `expert` option. More info can be found on [this stackexchange post](https://tex.stackexchange.com/a/548607/102530). A solution is also proposed in that post, but I have no idea how to integrate it into the latex class file. Simply replacing the `expert`  option and loading the `XCharter`  package seems to introduce an option clash, which I have no idea how to resolve.

**Comment by krono** [comment]
Thank you, I am aware of that.
For the warning to go away, we have to wait for `mathdesign` to catch up, which I don't want to side-step.
