### ISSUE TITLE
Overlapping DOI with licence authors on the Title page

### ISSUE THREAD

**Issue by mikepapadim** [programming-journal/programming#35]
I got an issue on the bottom of the title page with the authors and licenses.
The authors next to the license span into two lines and the DOI of the `\paperdetails` overlaps with names.

Is there a way to trim the names of the authors just for the licence placeholder on the title page?

**Comment by krono** [comment]
(can you please provide a screenshot?)

**Comment by mikepapadim** [comment]
![image](https://user-images.githubusercontent.com/8652854/92575162-ad9a3b80-f290-11ea-9ebd-a65b892cc83c.png)

**Comment by krono** [comment]
Thanks

**Comment by krono** [comment]
I suspect that the auhtors in the running head are equally too wide.

You can use  the `\authorrunning{...}` command to specifiy a short for of the authors. 

There is an example in the template file `example-programming.tex`:

```LaTeX
\authorrunning{T. Pape, C. Lopes, R. Hirschfeld} % Optional, for long author lists
```

**Comment by mikepapadim** [comment]
Indeed, authors and title in the running head are wide as well. However, both are split into two lines without breaking the text margins.

**Comment by krono** [comment]
I'm inclined to close this issue then.
