### ISSUE TITLE
Alignment of enumitem with custom labels

### ISSUE THREAD

**Issue by orestisfl** [programming-journal/programming#39]
When using a custom label with the `enumerate` environment the labels can spill outside the left margin.

MWE:
```tex
% -*- coding: utf-8; -*-
\documentclass[english,submission]{programming}

\usepackage[inline]{enumitem}
\usepackage{lipsum}

\title{MWE}
\author{MWE}
\begin{document}

\begin{abstract}
abstract
\end{abstract}

\lipsum
{%
\setlength\leftmargini  {2.5em}% Seems to be the original default
\begin{enumerate}[label=RQ\arabic*:, ref=RQ\arabic*]
\item With
\item modified
\item margin
\end{enumerate}%
}%
\begin{enumerate}[label=RQ\arabic*:, ref=RQ\arabic*]
\item With
\item programming's
\item margin
\end{enumerate}%
\lipsum

\end{document}

% Local Variables:
% TeX-engine: luatex
% End:
```

Screenshot:
![screenshot](https://user-images.githubusercontent.com/5778622/94227070-9ba7d200-fef9-11ea-85a9-257b7a933e18.png)

PDF:
[Programming.pdf](https://github.com/programming-journal/programming/files/5280624/Programming.pdf)

**Comment by krono** [comment]
Please do not use the `enumitem` Package safe for exceptional circumstance. Formal review would flag that.

**Comment by orestisfl** [comment]
Ok, thanks!
