### ISSUE TITLE
\area is required but not supported

### ISSUE THREAD

**Issue by brosenan** [programming-journal/programming#4]
When rendering our paper using the latest template, the  copyright notice at the bottom of the first page contains a message about a missing \area definition:
![missing \area](https://cloud.githubusercontent.com/assets/2514000/21841445/df405bfc-d7ea-11e6-801f-09e99507a07d.png)

However, after adding the line:
```latex
\area{Foo}
```
we got the following error:
```bash
! Undefined control sequence.
l.39 \area
          {Foo}
```
indicating that \area is not defined...

**Comment by krono** [comment]
This is a documentation issue. In fact, the `\area` command existed briefly before this template was published.

The correct way to do this is to add `area=...`  to `\paperdetails{..}`

fixed  in 70c1edb
