### ISSUE TITLE
Submitted/published date format

### ISSUE THREAD

**Issue by svdvonde** [programming-journal/programming#53]
Authors are provided metadata that is automatically inserted by the template. A part of this metadata includes the submitted/published dates. E.g.,

```
\paperdetails{
  submitted=2020-10-01,
  published=2022-02-15,
}
```

Given proper ISO dates, the template generates output such as:

> Submitted: 1st October 2020
> Published: 15th February 2022

This is different from the desired format requested by the publisher. They note:

> - For the publication information Submitted and Published,
  the date should be used as Month Day, Year (for example: February 15, 2022).

**Comment by krono** [comment]
What are your arguments to the `\documentclass` macro?

**Comment by svdvonde** [comment]
To the best of my knowledge I'm not using any exotic options.

```
\documentclass[crc,UKenglish]{programming}
```

**Comment by krono** [comment]
Please use plain `english`.

**Comment by svdvonde** [comment]
While this seems to solve the issue, it does not seem like a satisfactory solution going forward (there are differences between `english` and `UKenglish` regarding hyphenation). If the date must follow the specified format, it seems to be reasonable to generate the correct format rather than having it depend on the selected language.

A proposed solution can be found [here](https://github.com/svdvonde/programming/commit/2c99599084154e1cd80183c08c1645e6eb96c348). I can create a pull request if it is desirable.

**Comment by krono** [comment]
I am not comfortable with chaning the language as given in the [paper template](https://github.com/programming-journal/programming/blob/master/example-programming.tex#L3)

All hence published papers used the `english` option, including those by UK authors.
I'd kindly ask you to use the option :)

**Comment by svdvonde** [comment]
In that case the author guidelines probably require a slight rephrasing to avoid future confusion.

> All other options give in the `\documentclass` command are not processed directly by the class but rather passed on to other packages as “global options”. For example, the **english option from the example above does not influence the programming class directly, but rather will be picked up by Babel [2] to set up language options**.

(emphasis mine)

**Comment by krono** [comment]
Yes that is true.
And We probably need a more general decision as to whether there a degree of freedom in the choice of language variant for the Journal as a whole.

Can you please follow up with a mail? you find my contact in the paper template :)
