### ISSUE TITLE
Move \paperdetails command up in 'the minimal article' in the example

### ISSUE THREAD

**Issue by chiguri** [programming-journal/programming#57]
In example-programming.tex, `\paperdetails` command is placed just _before_ `\begin{document}`.
But _the minimal article_ (Listing 1 in the example) it is placed just after `\begin{document}`.
It is okay if it is used as-is, but if we add license to the `\paperdetails` command, the error occurs such as

> License set too late, move \paperdetailsup in the document

 (\paperdetailsup is not my typo, but as-is, and it makes me confused).

Are there any reason the `\paperdetails` command is placed there in __the minimal article_, the different place from the source of the example?

**Comment by krono** [comment]
HI

you are right, this ought to be fixed. Sorry
