### ISSUE TITLE
enumerate putting text between [ ] out of margins

### ISSUE THREAD

**Issue by melkyades** [programming-journal/programming#59]
The enumerate environment with [] items is generating output that [imho] looks nicer than description, but doesn't pass validations when uploading the paper for publishing, because the elements are out of the margin. See the attached screenshot

I had to change 

```
\begin{enumerate}
	\item [GCT -] Garbage Collector Tuning for a particular use case.
	\item [JITC -] Changing a JIT compiler to avoid recompiling
	methods too frequently.
	\item [CompO -] Optimizing the application with vector instructions added to the compiler.
\end{enumerate}
```

to

```
\begin{description}
	\item [GCT] - Garbage Collector Tuning for a particular use case.
	\item [JITC] - Changing a JIT compiler to avoid recompiling
	methods too frequently.
	\item [CompO] - Optimizing the application with vector instructions added to the compiler.
\end{description}
```

![image](https://github.com/programming-journal/programming/assets/315241/4c871a01-329d-4500-9b18-6a6d2164c236)

**Comment by krono** [comment]
Please use neither, omit the ` - `

```LaTeX
\begin{description}
	\item[GCT]  Garbage Collector Tuning for a particular use case.
	\item[JITC]  Changing a JIT compiler to avoid recompiling
	methods too frequently.
	\item[CompO] Optimizing the application with vector instructions added to the compiler.
\end{description}
```

It also seems you changed the appearence of descriptions. Please revert that.

**Comment by melkyades** [comment]
The screenshot was for using enumerate. Description works ok (with bold text, aligned from left margin). 

I guess the problem was I mixed enumerate with items that had [], which is not the standard way of using enumerations in latex. I'm just closing the issue.
