### ISSUE TITLE
\authorinfo does not show up in the pdf

### ISSUE THREAD

**Issue by brosenan** [programming-journal/programming#6]
For example:

 \authorinfo{Contact him at \email{lorenz@openu.ac.il}.}

**Comment by krono** [comment]
Can you provide more context?
I just re-tried this:
```LaTeX
\author{David H. Lorenz}
\authorinfo{Contact him at \email{lorenz@openu.ac.il}.}
```
before `\maketitle` and the information shows up as expected, on the last page in the “About the authors” section.
