### ISSUE TITLE
Incorrectly typeset date

### ISSUE THREAD

**Issue by lovrosdu** [programming-journal/programming#60]
Compiling the same document on two different machines produces differently typeset dates, even though both machines also use the same Tex Live 2021 installation. The results are consistent and so far I haven't been able to identify the cause. I suspect the `useregional` option passed to `datetime2` might have something to do with it.

Wrong:
![wrong](https://github.com/programming-journal/programming/assets/77115031/8c7fd440-651a-4074-a115-4da7fc90d922)

Correct:
![correct](https://github.com/programming-journal/programming/assets/77115031/f5c26246-8cd0-4243-a1b4-7ffa0d59a120)

**Comment by lovrosdu** [comment]
Hi! Here's a complete MRE instead (but let me know if you need the log file still). No language options other than `english` are used. The issue is present whether compiling with pdfTeX or LuaTeX.

```latex
\documentclass[english]{programming}

\paperdetails{
  submitted=2021-01-01,
  published=2021-01-02
}

\begin{document}

\begin{abstract}
  Lorem ipsum.
\end{abstract}

\end{document}
```

Removing the `english` option makes both machines produce the "wrong" output.

**Comment by krono** [comment]
Thanks.
Can you pleas attach the Log files from both runs?

**Comment by krono** [comment]
Also, can you try running latex with `LANG=en_us.UTF-8` environment setting?

**Comment by lovrosdu** [comment]
Here are the two logs. Yep, both of the machines already have `LANG` set to `en_US.UTF-8`.

- [main-wrong.log](https://github.com/programming-journal/programming/files/13215862/main-wrong.log) (uses a local Tex Live 2021 installation)
- [main-correct.log](https://github.com/programming-journal/programming/files/13215864/main-correct.log) (uses the system Tex Live 2021 installation)

**Comment by krono** [comment]
Both installations differ quite substantially.
In particular:
- `babel` "2021/04/26 3.58" vs "2022/02/26 3.73"
- format of `lualatex` "2023.5.28" vs "2023.10.27"
- LaTeX2e ""<2021-11-15> patch level 1" vs "<2020-10-01> patch level 4"

Also, I am seeing 
```
Package babel Info: You haven't specified a language. I'll use 'nil'
(babel)             as the main language.
```
Which surely can be a cause of problems. I have never seen this issue before.
Also `doclicense` is complaining: 
```
Package doclicense Warning: The language of your document is not defined.
```


This has never occured before to me.

[This not completely dissimilar issue suggests that maybe a system package (maybe `texlive-babel-english`?) is mising](https://tex.stackexchange.com/questions/309002/lyx-package-babel-error-you-havent-specified-a-language-option)  
Maybe worth a shot?

**Comment by lovrosdu** [comment]
Sorry, I erroneously left out the `english` option in both of the above runs when producing the logs. Here are the corrected logs:

- [main-wrong-english.log](https://github.com/programming-journal/programming/files/13221713/main-wrong-english.log)
- [main-correct-english.log](https://github.com/programming-journal/programming/files/13221714/main-correct-english.log)

With the addition of `english`, the above errors disappear. However, taking a closer look at the "wrong" log this time, I noticed this line:

```
Package datetime2 Warning: Date-Time Language Module `english' not installed on
 input line 1913.
```

Installing `datetime2-english` (via `tlmgr` in my case since it's a local installation; no system packages required) was enough to correct the issue.

I assume `babel-english` and `datetime2-english` are both "silent" dependencies of this class file, meaning that the compilation won't necessarily fail if they're not present, but will produce unexpected results. It would be nice to make these packages a hard requirement and produce an error instead if possible.

**Comment by krono** [comment]
Good to see this is solved for you.

There is no package dependency management facility for plain LaTeX class files. I have no way to fix that.
