### ISSUE TITLE
Template repository?

### ISSUE THREAD

**Issue by khatchad** [programming-journal/programming#68]
Shouldn't this be a "template" repository, so that one may start a new paper from it?

**Comment by krono** [comment]
That's a neat Idea and already halfway there: [example-programming.tex](https://github.com/programming-journal/programming/blob/main/example-programming.tex) can already be used as a starting point.

What's missing from your point of view?

**Comment by khatchad** [comment]
Thanks! The button on GitHub :). https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by khatchad** [comment]
But, that could be prohibitive if you already have a repository and just want to copy the class and example files.

**Comment by khatchad** [comment]
Still, I believe one may clone a template repository.

**Comment by krono** [comment]
There's now a "use this template" button in addtition to the ones already existing
