### ISSUE TITLE
Inconsistent font between captions and references

### ISSUE THREAD

**Issue by brosenan** [programming-journal/programming#7]
The digit 1 appears sometimes as a an Arabic numeral (1) and sometimes as a Roman numeral (I).  This is especially a problem in some cases where the caption for an object uses one representation, and references to this object use the other representation.  The images below are taken from a footnote in the example provided with this project.
The reference to the footnote uses Arabic numerals:
![image](https://cloud.githubusercontent.com/assets/2514000/22034040/89603b7c-dcf3-11e6-8ab3-6c47230594a1.png)
and the caption in the footnote itself uses Roman numerals:
![image](https://cloud.githubusercontent.com/assets/2514000/22034066/9c312018-dcf3-11e6-87d9-3100860ad796.png)

In our paper, reference to Fig. 1 uses Roman numerals:
![image](https://cloud.githubusercontent.com/assets/2514000/22034248/55885da6-dcf4-11e6-8670-2cad90c2a1b9.png)
while the caption of that figure uses Arabic numerals:
![image](https://cloud.githubusercontent.com/assets/2514000/22034274/6c91e0da-dcf4-11e6-9e8e-98dc8f8b5f78.png)

**Comment by krono** [comment]
Thanks for the information.

Please note that the seemingly roman numerals are, in fact, [text figures](https://en.wikipedia.org/wiki/Text_figures). 
The sans-serif used for Figure captions is Fira Sans, which does not posses text figures:

<img width="264" alt="bildschirmfoto 2017-01-17 um 19 41 04" src="https://cloud.githubusercontent.com/assets/119279/22034849/fe21d99e-dced-11e6-9c1c-a5a972c1df99.PNG">

The inconsistency between footnote definition and reference is indeed strange. Alas, I cannot reproduce this here.

PS: Please do not use 'Fig. 1' with the `programming` class. Either write `Figure \ref{..}` or better  `\autoref{...}`

**Comment by brosenan** [comment]
We used:
```latex
Fig.~\ref{fig:A-Comparison-between}
```
in our source code

**Comment by krono** [comment]
Please use either

```LaTeX
Figure~\ref{fig:A-Comparison-between}
```
or (preferred) 
```LaTeX
\autoref{fig:A-Comparison-between}
```

**Comment by brosenan** [comment]
The use of the XCharter OS font for numbers can be misleading.  For example:
![image](https://cloud.githubusercontent.com/assets/2514000/22054557/dbbbf0b2-dd5e-11e6-94b7-0aef76f0556d.png)
refers to:
![image](https://cloud.githubusercontent.com/assets/2514000/22054586/fb1d25c0-dd5e-11e6-8672-1db48a02830e.png)
but actually looks like it refers to figure 2 (II being Roman 2).

**Comment by krono** [comment]
I can understand that.
However, if there is a figure 11, there has already been figures 1 and 2, and confusion is avoided.
Also note that this would only look too similar if someone used small caps roman numerals:

![bildschirmfoto 2017-01-18 um 10 30 31](https://cloud.githubusercontent.com/assets/119279/22058446/2ea21bc6-dd69-11e6-92fd-b32e8ec4a9f4.PNG)

**Comment by dhlorenz** [comment]
Note that \autoref{fig:A-Comparison-between} produces "figure~"... instead of "Figure~"''... because
\figureautorefname}{figure}.  You may want to fix that in programming.cls

**Comment by krono** [comment]
Yea, I that was a s;o[ above. 

"figure .." (lowercase) is the preferred spelling. (as is "table" and "listing")

**Comment by dhlorenz** [comment]
Chicago vs. APA style... 
What about Sect. vs Section vs section?
BTW, when referring to a Figure in the text, the word "Figure" is usually abbreviated as "Fig.", while "Table" is not abbreviated. Both words are spelled out completely in descriptive legends.

**Comment by krono** [comment]
Here's the relevant part:

```LaTeX
\defcaptionname{english}{\figureautorefname}{figure}
\defcaptionname{english}{\tableautorefname}{table}
\defcaptionname{english}{\lstlistingautorefname}{listing}
\defcaptionname{english}{\lstnumberautorefname}{line}
\defcaptionname{english}{\subsectionautorefname}{\sectionautorefname}
\defcaptionname{english}{\subsubsectionautorefname}{\sectionautorefname}
```

Since `\sectionautorefname` is “section”, both subsections and subsubsections also use this term.

In short:
All reference names are _lowercase_ and _spelled out_.

**Comment by brosenan** [comment]
We moved to using ```\autoref```, but we see the following issues:
- The words Appendix and Equation are shown capitalized
- \autoref is ignorant of actual capitalization rules, so if a sentence begins with a reference to, e.g., a table or a figure, it will begin with a lowercase letter.

**Comment by dhlorenz** [comment]
Problem alleviated by using \usepackage[noabbrev]{cleveref}, which provides \cref and \Cref as alternatives to \autoref

**Comment by krono** [comment]
Again, thanks for the feedback.
