### ISSUE TITLE
Adding an image to \authorinfo

### ISSUE THREAD

**Issue by brosenan** [programming-journal/programming#8]
Is there a way to add pictures of the authors to the \authorinfo section?

**Comment by krono** [comment]
Yes, see the template/example:

>  You can use the `\authorinfo` command right after an `\author` command to associate that author information with an author. See line 27 in listing 2 for example. The photo is given as optional argument as file name in brackets (without file extension). Omitting the photo will produce a blank space next to the author information. 

> 27 % Author information
28 \author{Anna Author}
29 \authorinfo[anna]{is a researcher at the Unseen University in Ankh−Morpork and
30 a Ph\,D student to Rincewind. Contact her at
31 \email{anna.the.author@univ−unseen.edu.pratchett}}
32 \affiliation[a]{The Unseen University, Ankh−Morpork}

In this case (line 29), a picture starting with `anna` (eg, `anna.pdf`, `anna.jpg`, or `anna.png`) 
will be used.
